
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
include: ["_pages"]

name: ARTIS
title: ARTIS | Architectural and structural metalwork
baseurl: /
keywords: artis, image

# HEADER STRINGS #
site_logo_string: "ARTIS"
why_artis_url: "/why-artis/"
products_and_services_url: "/products-and-services/"
contact_url: "#contact-section"
cta_btn_url: "mailto:someone@yoursite.com"
cta_btn_icon: "mail_outline"
mobile_cta_btn_url: "tel:00381668019888"
mobile_cta_btn_text: "MAKE A CALL"
mobile_cta_btn_icon: "call"


home_title: Architectural & <br> structural metalwork
home_description: Creating a customized solution of your dreams. Let a team of highly skilled draughtsmen, fabricators and designers to give the best of themselves when delivering quality and satisfaction along with the work of art YOU desire.

about_section_paragraph01: <strong>ARTIS</strong> is a fresh name on the market , recently established by a small team of humble and hardworking steel fabricators with 25 years of knowledge and experience in the field.
about_section_paragraph02: The passion for innovation and remarkable results brought them together and here is how ARTIS came to life.Creating is about new dimensions , thinking forward, transforming, pushing boundaries in long hours of work. Name it art and trust that your project will be in safe hands here.